### ISSUE TITLE
change in windows registry path

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapySDRPlay3#30]
The build is looking for `GET_FILENAME_COMPONENT(SDRPLAY_API_DIR "[HKEY_LOCAL_MACHINE\\SOFTWARE\\SDRplay\\API;Install_Dir]" ABSOLUTE)`: https://github.com/pothosware/SoapySDRPlay3/blob/master/FindLibSDRplay.cmake

But the installer is placing the registry path in `[HKEY_LOCAL_MACHINE\\SOFTWARE\\SDRplay\\Service\\API` with the Service subdirectory in there

I think this should be change, I just want to make sure this is intentional going forward

**Comment by SDRplay** [comment]
Confused what this is? API 3 always goes in SDRplay\Service\API - API 2 went into SDRplay\API

Is that a problem??

**Comment by guruofquality** [comment]
Not a problem, Our current FindLibSDRplay.cmake in this repo is just incorrect and I wanted to confirm before just changing it

**Comment by fventuri** [comment]
Thank @guruofquality and @SDRplay - I just fixed `FindLibSDRplay.cmake` and pushed it to master

Franco
