### ISSUE TITLE
Make a tag/release

### ISSUE THREAD

**Issue by AsciiWolf** [pothosware/SoapySDRPlay3#51]
Please, consider making a tag or a release for SoapySDRPlay3. It would make packaging in Linux distributions much easier.

**Comment by fventuri** [comment]
Good idea @AsciiWolf
I just published the tag 0.4.0 (`soapy-sdrplay3-0.4.0`) with the current code, add a note in the Changelog file, and I'll be starting making consistent use of them from now on.

Franco

**Comment by AsciiWolf** [comment]
Thanks! :-)
