### ISSUE TITLE
dll not recognized by Soapy (Windows 11)

### ISSUE THREAD

**Issue by jmillo** [pothosware/SoapySDRPlay3#63]
I am a newbie in installing stuff under Windows.
I have a perfectly working gnuradio installation under Ubuntu and am trying to port it to Windows 11.
To be able to use my RSP1A , I generated the .so under Linux and copied it in the directory where Soapy has it's modules and it worked at first try.
On Windows, I tested the RSP1A with SDRUNo and it works.
Under Windows, I used cmake and got a .sln file that created a release version (with Visual studio 2019 and 2022 ,both were identical) and copied the resulting .dll (sdrPlaySupport.dll) under SoapySDR/modules0.8 where the others are.
Then I ran in the following problem:

(radioconda) C:\Users\Jean\SoapySDRPlay3\build>soapysdrutil --info
######################################################
######################################################

Lib Version: v0.8.1-2
API Version: v0.8.0
ABI Version: v0.8
Install root: D:\Anaconda3\envs\radioconda\Library
Search path:  D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/airspyhfSupport.dll (0.2.0)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/airspySupport.dll   (0.2.0)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/bladeRFSupport.dll  (0.4.1)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/HackRFSupport.dll   (0.3.4)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/LMS7Support.dll     (22.09.0)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/PlutoSDRSupport.dll (0.2.1)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/remoteSupport.dll   (0.5.2)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/rtlsdrSupport.dll   (0.3.0)
Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/sdrPlaySupport.dll
  LoadLibrary() failed: The specified module could not be found.

Module found: D:\Anaconda3\envs\radioconda\Library/lib/SoapySDR/modules0.8/uhdSupport.dll      (0.4.1)
Available factories... airspy, airspyhf, bladerf, hackrf, lime, plutosdr, remote, rtlsdr, uhd
Available converters...
 -  CF32 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS16 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS32 -> [CS32]
 -   CS8 -> [CF32, CS16, CS8, CU16, CU8]
 -  CU16 -> [CF32, CS16, CS8]
 -   CU8 -> [CF32, CS16, CS8]
 -   F32 -> [F32, S16, S8, U16, U8]
 -   S16 -> [F32, S16, S8, U16, U8]
 -   S32 -> [S32]
 -    S8 -> [F32, S16, S8, U16, U8]
 -   U16 -> [F32, S16, S8]
 -    U8 -> [F32, S16, S8]

(radioconda) C:\Users\Jean\SoapySDRPlay3\build>

Just to be sure, although I have the latest API,  I tried the same trick with SoapySDRPlay (not 3) : same result.

There must be something very evident that escapes me.
Can anybody help?

**Comment by fventuri** [comment]
@jmillo - I am not a Windows expert in the least (I too use Linux 99% of the time), but when I used the conda/radioconda installer for another piece of code I wrote (the GNU Radio OOT module 'gr-sdrplay3'), I found out that conda for Windows looks for DLLs only in a few folders (no matter what the environment variable PATH is set to):

- the folder where the sdrPlaySupport.dll is located
- %CONDA_PREFIX%
- %CONDA_PREFIX%\Library\mingw-w64\bin
- %CONDA_PREFIX%\Library\bin
- %CONDA_PREFIX%\Scripts
- C:\Windows\System32

so I had to copy the SDRplay API DLL ('sdrplay_api_dll') to one of those folders. This post that I wrote a while ago to the GNU Radio mailing list has some more details: https://lists.gnu.org/archive/html/discuss-gnuradio/2022-03/msg00144.html

Hope this helps,
Franco

**Comment by jmillo** [comment]
Thanks @fventuri ,
that was it sdrplay_api.dll was not visible.

I will also try your package.

Regards,
J.M.
