### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by ghost** [pothosware/SoapySDRPlay3#89]
I tried to build this on a Debian Bookworm laptop. I cloned the repository and mkdir build etc. I get this:

cmake ..
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "SoapySDR"
  (requested version 0.4.0) with any of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

thanks

**Comment by jketterl** [comment]
`apt-get install libsoapysdr-dev`

That is distribution specific information however, so it's not part of the installation instructions. It's basically expected that you know how to set up the dependencies when you compile stuff.
